version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 3000
      DB_PORT: 5432
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: ashutosh
      DB_NAME: bitespeed
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ashutosh
      POSTGRES_DB: bitespeed
    ports:
      - '5432:5432'
